### ISSUE TITLE
Where is the server

### ISSUE THREAD

**Issue by hassanzadeh** [psugihara/FreeChat#38]
Hey Guys,
Question, so how is the executable server created? Is it done by llama.cpp project?

**Comment by psugihara** [comment]
Yes, the server is llama.cpp/examples/server running on localhost.

I make a universal binary by compiling it on an arm and intel machine then combining them with:
`lipo -create server server_x86 -output freechat-server`

**Comment by hassanzadeh** [comment]
Interesting when you said compile, you mean running "make -j +[arch related args]" in llama.cpp ?

**Comment by psugihara** [comment]
yes

**Comment by hassanzadeh** [comment]
Got it thanks,
Sorry I see there is another executable server-watchdog what is that doing? and how does that work?
