### ISSUE TITLE
Crash on sending prompt

### ISSUE THREAD

**Issue by sussyboiiii** [psugihara/FreeChat#66]
Im in the Beta, macOS Sonoma, M1 Pro 16GB, loading any model crashed even small ones which worked beforehand.

**Comment by psugihara** [comment]
Hm, i wonder if the models you're using aren't compatible with the latest llama.cpp anymore (llama.cpp periodically breaks compatibility). That's the only substantive change in the latest beta.

**Comment by psugihara** [comment]
If you have time, can you download a recently quantized model and let me know if it works?

**Comment by sussyboiiii** [comment]
Hello, I used the newest llama.cpp version and the same model

<img width="1728" alt="Screenshot 2024-04-25 at 19 47 33" src="https://github.com/psugihara/FreeChat/assets/90244617/de38f12a-af46-4887-a0c5-304a2e7238da">

**Comment by sussyboiiii** [comment]
Tested two models both crashed in FreeChat and worked in the terminal.

**Comment by psugihara** [comment]
dang, no good! thanks for testing.

i'm doing a refactor at the moment to simplify a few things and I'll try to figure out what's causing it.

**Comment by sussyboiiii** [comment]
After updating FreeChat it now doesn't crash anymore.

**Comment by sussyboiiii** [comment]
Where did the ability to change the system prompt go? Can't find it anymore.

**Comment by psugihara** [comment]
that's great news! thanks for testing again.

> Where did the ability to change the system prompt go? Can't find it anymore.

I still see it in the FreeChat > Settings panel:

<img width="647" alt="Screenshot 2024-04-26 at 8 19 27 AM" src="https://github.com/psugihara/FreeChat/assets/282016/c5f8326c-6981-442b-9631-d53d024dd5b4">
<img width="647" alt="Screenshot 2024-04-26 at 8 19 24 AM" src="https://github.com/psugihara/FreeChat/assets/282016/c7278063-aa42-42a0-a73d-cd213332fe8e">

**Comment by sussyboiiii** [comment]
Oh well, I ment the tab to choose the template or whatever it's called where I can choose between Vicuna or e.g. ChatML.

**Comment by psugihara** [comment]
Yes, I have removed that and now defer to llama.cpp's conversation templating. The prompt formats are now embedded in GGUFs so that inference servers (like the llama.cpp server we use) can do it correctly themselves. This makes freechat a lot easier to maintain because I don't have to hardcode template formats (and model -> template mappings) myself.
